[tool.poetry]
name = "wsvcs"
version = "0.1.0"
description = ""
authors = ["Encore Ecosystem"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
websockets = "^13.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
